baseURL = 'https://eric-hansen.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "hugo-theme-monochrome"
hasCJKLanguage = true
defaultContentLanguage = "en"
enableEmoji = true

[outputs]
home = ["HTML", "RSS", "JSON"]
