[[navbar]]
identifier = "about"
name = "About"
title = "about"
url = "/about/"
weight = 1

[[navbar]]
identifier = "cv"
name = "Resume"
title = "resume"
url = "/resume/"
weight = 2

[[navbar]]
identifier = "posts"
name = "Posts"
url = "/posts/"
weight = 3

[[navbar]]
identifier = "series"
name = "Series"
url = "/series/"
weight = 4

[[navbar]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 5